Run uStreamer via a launcher
tiny-pilot/ansible-role-ustreamer pull request #89
Opened 2022-12-28 06:15 UTC by mtlynch

2023-01-04 16:03 UTC, mtlynch commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/89)

⏳ @jdeanwallace please review this Pull Request

2023-01-05 14:37 UTC, jdeanwallace requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/89)



<hr />

In: **files/launch**:

```
> Line 55
  yaml_value="$(cat /opt/ustreamer-launcher/configs.d/* | yq "${yaml_path}")"
```
I'm confused about how this bash command works. I did some local testing with multiple yaml files and `yq` doesn't merge the yaml files by default:
```bash
$ ls /tmp/*.yml
/tmp/a.yml  /tmp/b.yml
$ cat /tmp/*.yml
---
ustreamer_persistent: yes

---
ustreamer_persistent: off

$ cat /tmp/*.yml | yq '.ustreamer_persistent'
yes
---
off
```

I followed [these `yq` docs](https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#merge-combine-all-documents-into-one) to merge all the yaml files together:
```bash
$ cat /tmp/*.yml | yq eval-all '. as $item ireduce ({}; . * $item ) | .ustreamer_persistent'
off
```

<hr />

In: **files/launch**:

```
> Line 111
/opt/ustreamer/ustreamer "${USTREAMER_ARGS[@]}"
```
Can we use [`exec`](https://man7.org/linux/man-pages/man3/exec.3.html) here so that it replaces the current process?



<hr />

In: **tasks/install_launcher.yml**:

```
> Line 9
    ustreamer_yq_architecture: "{% if ansible_architecture == 'x86_64' %}amd64{% elif ansible_architecture == 'armv7l' %}arm{% elif ansible_architecture == 'aarch64' %}arm64{% else %}{{ ansible_architecture }}{% endif %}"
```
(optional) To avoid the if-else statements, we could also define the architecture mapping as a dictionary. For example:

```yaml
# This can be defined as a fact or as a default value in `defaults/main.yml`
- name: define ansible to yq architecture mapping
  set_fact:
    ustreamer_yq_arch_map:
       x86_64: amd64
       armv7l: arm
       aarch64: arm64

# This can be defined as a fact or as a default value in `defaults/main.yml`
- name: canonicalize yq binary architecture
  set_fact:
    ustreamer_yq_arch: "{{ ustreamer_yq_arch_map[ansible_architecture] | default(ansible_architecture) }}"
``` 

<hr />

In: **tasks/install_launcher.yml**:

```
> Line 26
- name: create uStreamer launcher configs folder
```
(optional) We could also collapse the creation of the above 2 directories into a single task using `loop`. For example:

```yaml
- name: create uStreamer launcher directories
  template:
    path: "{{ item }}"
    state: directory
    owner: "{{ ustreamer_user }}"
    group: "{{ ustreamer_group }}"
  loop:
    - "{{ ustreamer_launcher_dir }}"
    - "{{ ustreamer_launcher_configs_dir }}"
```

<hr />

In: **vars/main.yml**:

```
> Line 15
ustreamer_launcher_script: /opt/ustreamer-launcher/launch
```
Can we use the `ustreamer_launcher_dir` variable to build the path? Something like:
```yaml
ustreamer_launcher_script: "{{ ustreamer_launcher_dir }}/launch"
```


<hr />

👀 @mtlynch it's your turn please take a look

2023-01-05 20:46 UTC, mtlynch reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/89)



<hr />

In: **files/launch**:
Whoops, that's embarrassing. Thanks for catching that!

I tested for this issue and found a similar solution, but I must have just applied it on the command-line during testing and forgot to integrate it back into the script.

I blame it on holiday brain. 

<hr />

In: **files/launch**:
Sure, that sounds fine. What's the advantage in this case? I get the idea of replacing the process as opposed to starting a subshell, but I'm not clear on the implications.

<hr />

In: **tasks/install_launcher.yml**:
Oh, nice! I like that. Fixed.

<hr />

In: **tasks/install_launcher.yml**:
Oh, yeah this is so much cleaner. Thanks!

<hr />

In: **vars/main.yml**:
Sure, fixed.


<hr />

👀 @jdeanwallace it's your turn please take a look

2023-01-06 14:54 UTC, jdeanwallace requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/89)


⏳ Approval Pending (3 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

Looks good and I've tested it on device. Changing video settings is super fast now!

<hr />

In: **files/launch**:
From what I [understand](https://unix.stackexchange.com/a/286383), using `exec` cuts out the middleman process and preserves termination signals which I think is important for systemd to make restart decisions.

<hr />

In: **files/launch**:

```
> Line 45
MERGED_YAML="$(yq eval-all '. as $item ireduce ({}; . * $item )' \
```
(nit): Can we mark `MERGED_YAML` as `readonly` after setting its value?

<hr />

In: **files/launch**:

```
> Line 82
     [[ "${yaml_value_lowercase}" != 'no' ]]; then
```
(nit, optional): Would this if statement become clearer if we matched the positive condition? For example:

```bash
  if [[ "${yaml_value_lowercase}" == 'true' ]] && \
     [[ "${yaml_value_lowercase}" == 'on' ]] && \
     [[ "${yaml_value_lowercase}" == 'yes' ]] && \
     [[ "${yaml_value_lowercase}" == 'y' ]]; then
```

(Reference: [Possible yaml boolean values](https://yaml.org/type/bool.html))

<hr />

In: **tasks/install_launcher.yml**:

```
> Line 79
    mode: '0755'
```
Can we restart uStreamer if the launcher file changes? Something like:
```yaml
notify: restart uStreamer
```


<hr />

👀 @mtlynch it's your turn please take a look

2023-01-06 16:36 UTC, mtlynch reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/89)



<hr />

In: **files/launch**:
Oh yeah, that's a good idea. I was thinking that anything that isn't false is implicitly true (e.g., `ustreamer_persistent: banana`) counts as true, but we don't need to be so permissive, and it's clearer to just allow the explicit things we expect.

<hr />

In: **files/launch**:

```
> Line 45
MERGED_YAML="$(yq eval-all '. as $item ireduce ({}; . * $item )' \
```
Ah, right. Fixed.

<hr />

In: **tasks/install_launcher.yml**:

```
> Line 81
    mode: '0755'
```
Oh, good point. I added it to the "write uStreamer runtime variables to file" play as well.

2023-01-06 16:46 UTC, merged